version: '2'

services:
  font:
    image: minted/fonts
    build: .
    container_name: "fonts"
    expose:
      - "3000"
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      NODE_ENV: production

